workflows:
  ios-workflow:
    name: Compilar iOS de AssetDesk
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Instalar dependencias
        script: |
          flutter pub get
      - name: Construir app para iOS sin firma
        script: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r assetdesk.ipa Payload
    artifacts:
      - assetdesk.ipa